code_root_dir: <YOUR_PATH>/
cv_split_dir: ${.code_root_dir}cv_splits_paper/cv_splits_sote_multi_stratified_sklearn_s_a_paper_patients_rev/
emb_dim: 1024
lr: 2.0e-05
use_scheduler: false
initial_lr: 5.0e-05
eta_min: 5.0e-07
weight_decay: 0.01
minority_class_ratio: 1.0
sampling_exponent: 0.5
num_epochs: 50
batch_size: 1
n_experiment: 1
n_classes: 3
run_nr: sote_sqrt_paper_rev_tuned
results_dir: <YOUR_PATH>/run_${.run_nr}/
dropout_fc: 0.6
dropout_attn: 0.6
hidden_dim: 256
att_hidden_dim: 256
